### ISSUE TITLE
Unique name generator is not unique

### ISSUE THREAD

**Issue by urubens** [Cytomine-ULiege/pims#21]
https://github.com/Cytomine-ULiege/pims/blob/cb655acb5d69d4fa55e0090615f6cdd493184e7d/pims/utils/strings.py#L18

When a new file is imported, it is stored in a directory `upload${unique_name_generator()}` and it is required that this directory is unique across all imports. However, this generator inspired by Cytomine-IMS does not enforce such uniqueness as 2 simultaneous imports would results in the same `uploadX` directory, breaking thus the hard constraint of 1 import by `upload` directory which is imposed by PIMS implementation.

Need to be replaced by a true unique name generator.

**Comment by geektortoise** [comment]
@chlmarchal : Can you change the unique name generator by a UUID (I think there exist some existing feature for that) :-)
