### ISSUE TITLE
Format tests not working with custom root

### ISSUE THREAD

**Issue by urubens** [Cytomine-ULiege/pims#29]
All test formats hardcode `/data/pims` as file root in tests.  When another root is used, all tests are failing. These tests are only working if https://github.com/Cytomine-ULiege/pims/blob/c4b9cd46265ab6c6c4ce05fc3696fbba303248a8/tests/conftest.py#L73
return `/data/pims` while it should be more flexible.

By the way, the default test config uses https://github.com/Cytomine-ULiege/pims/blob/c4b9cd46265ab6c6c4ce05fc3696fbba303248a8/tests/pims-config.env#L1
which makes these tests failing with default config :/.

**Comment by chlmarchal** [comment]
https://github.com/Cytomine-ULiege/pims/pull/31
