### ISSUE TITLE
Implement image file deletion

### ISSUE THREAD

**Issue by urubens** [Cytomine-ULiege/pims#6]
In Cytomine-IMS, it is possible to delete image files. 

## Delete a representation of a valid image
e.g. delete the original file while the image is still used in Cytomine

It is possible to delete image files that are not used for visualization, from the Storage tab, such as:
1. Intermediary converted files
2. Original uploaded files

It seems it is allowed to delete visualization files (e.g.`_pyr.tif` files), but breaking thus the viewer. Not sure about a use-case it should be allowed. (However, this is more a Cytomine-core responsibility).

With PIMS:
1. Intermediary conversion shouldn't exist anymore, and if really needed, the intermediary file should be deleted by PIMS after conversion.
2. Much complex:
    - Imported archive with multi-file format: can be deleted as it is useless to keep the packed content next to the unpacked content. For original file export, archive can be computed on the fly with the unpacked directory (as Cytomine-IMS do), while it can be an expensive task...
    - Imported archive with multiple images from various formats (#3): same as above. When we want to export the file `x.jpg` that was in the archive, I guess the `x.jpg` should be given instead of the whole archive.
    - Original files that are converted (example: a big JPEG converted to pyramidal TIFF): Here we have a problem. With PIMS, both the original file and the visualization file are useful. Metadata are read from the original file (and never copied to the visualization file) while tiles are read from the visualization file. 

It could be great to clarify usages of image file deletion because deleting original image file breaks image download/export. I understand the need for disk usage constraints but I have the feeling Cytomine-Core is not enough ready to deal with deleted image file representation for a valid image.

Put this aside, for the latter case, I see this solution: When I delete an original file, I extract all metadata and save them in a metadata JSON file at original file location.  The JSON can be read when metadata is needed. However, it requires supplementary developments to support this.

## Delete an image and all its representations
When an Abstract Image is deleted, delete all related files (original, visualization, histogram, ...). Easy with PIMS, as we only have to delete the related upload folder.

# Proposal for PIMS V1.0
It is possible to delete:
1. archive file (but the unarchived content is kept)
2. intermediary converted file (no more used by PIMS, they even could be deleted at migration step (?))
3. an image and all its representations (original, converted, ...) at once

It it not possible to delete representations of a **not-Cytomine-Core-deleted** image, including:
1. original image file -- This is a regression. Temporary until implementation of metadata JSON ?
2. ~~visualisation image file -- This is a regression. But it shouldn't be allowed.~~ [Edit: it is already not allowed]

**Comment by urubens** [comment]
@geektortoise Could you clarify the use cases of the uploaded file deletion features ? What do you think about PIMS V1.0 proposal ?

**Comment by geektortoise** [comment]
The uploaded file deletion features was originally to gain some disk space for original converted file (included archive).
When we add
zip
- formatX
- format.ome.tiff
- format.pyr_tiff

Only the last file was really used.

+ in some case, the image instances was deleted, the project also and we just don't need or want the images on the disk. A simple example is a test case on a Cytomine instance: 
- "I upload a pic of my face"
- "okay, it works"
- "Uhuh. How do I delete it ?"

If somebody (a person as a company want (GDPR) all its images (and data)) deleted, it should be possible. How will we manage that ? :/

On Current IMS there is no check that an image is used but the Core doesn't allow the deletion of a used image (responsability is splitted here)

**Comment by urubens** [comment]
I slightly updated my previous comment because it was confusing (but it is probably still confusing ;) ). 

Yes that's true that Core will prevent deletion of the pyr.tiff image if used (but the button is shown in the UI, and the message is shown after trying deletion but it's an other story :) )

If I upload a pic of my face (and in the background we have myface.jpg, myface_pyr.tiff, ....).
1. I want to delete my face from the server: Okay we delete myface.jpg and all related underlying files surch as myface_pyr.tiff ("Delete an image and all its representations")
2. I want to delete the original "myface.jpg" from the server to gain disk space and keep the converted file: 
    - OK with IMS 
    - But not ok with PIMS, because we need the "myface.jpg" to get image metadata and "myface_pyr.tiff" to get tiles.

So the idea is, for a given upload, delete all dependent files or nothing (with the exception of archive that can be replaced by the archive content). 

The (temporary) regression is it is no more possible to delete the original image (for disk space) if I want to continue to use my image because now, PIMS needs also this file to continue to use my image.

**Comment by iRyoka** [comment]
Dear developers, do I understand correctly, that the current veriosn of PIMS does not have ANY uploaded files delete method implemented? 

According to [API](https://github.com/Cytomine-ULiege/pims/blob/3ff96c4c4caf0142fe43954d14adfaa886ccdb95/pims/openapi/api-specification.yaml#L1879) the method responsible for deletetion is https://github.com/Cytomine-ULiege/pims/blob/3ff96c4c4caf0142fe43954d14adfaa886ccdb95/pims/api/operations.py#L205 which is not implemented.

A connected question: if an uploaded file is deleted form cytomine (via ui or api), is it safe to simply delete the corresponding dir in the `images` folder controlled by PIMS? I'm in an urgent need to free up some space.
